### ISSUE TITLE
C++ Core GuideLines explained 有兴趣和计划翻译么

### ISSUE THREAD

**Issue by WangFengtu1996** [xiaoweiChen/The-CXX-Library-Fourth-Edition-include-CXX23#2]
* 如题。

**Comment by xiaoweiChen** [comment]
目前这本书，我这边没有PDF的版本，有的话，可以分享一下

**Comment by WangFengtu1996** [comment]
* z-lib 目前确实没有pdf版本，sorry，我这边也没有哈

**Comment by sarendis56** [comment]
如果是2022年的C++ Core Guidelines Explained: Best Practices for Modern C++的话我有PDF版本，如果还需要的话可以发到你邮箱

**Comment by xiaoweiChen** [comment]
@Hyle33ies  loongchen25@126.com 
发送完了，可以在这里提示我一下，我看邮箱看得比较少

**Comment by sarendis56** [comment]
> @Hyle33ies [loongchen25@126.com](mailto:loongchen25@126.com) 发送完了，可以在这里提示我一下，我看邮箱看得比较少

@xiaoweiChen 你好，已经发送了

**Comment by xiaoweiChen** [comment]
已收到，多谢。后续会安排上，请耐心等待哈

**Comment by xiaoweiChen** [comment]
@WangFengtu1996 @Hyle33ies 这本书已经有中文译版发售了，我这边就不再进行翻译了。
[当当的链接](https://product.dangdang.com/29605935.html?_ddclickunion=P-306226-132902978-s36513376|ad_type=0|sys_id=1#dd_refer=https%3A%2F%2Fbook.douban.com%2Flink2%2F%3Flowest%3D7480%26pre%3D0%26vendor%3Ddangdang%26srcpage%3Dsubject%26price%3D12540%26pos%3D2%26url%3Dhttps%253a%252f%252funion.dangdang.com%252ftransfer.php%253ffrom%253dp-306226-132902978-s36513376%2526backurl%253dhttps%253a%252f%252fproduct.dangdang.com%252fproduct.aspx%253fproduct_id%253d29605935%26cntvendor%3D3%26srcsubj%3D36513376%26type%3Dbkbuy%26subject%3D36513376)

**Comment by guanbo123456** [comment]
@Hyle33ies 534945456@qq.com 麻烦发我一下，谢谢
